# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:17
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('core', 'Child')
    for row in MyModel.objects.all():
        row.unique_id = uuid.uuid4()
        row.save()

    MyModel = apps.get_model('core', 'ChildParents')
    for row in MyModel.objects.all():
        row.unique_id = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_uuid_fields'),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
