# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_uuid_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='childparents',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
